version: '3.3'

services:
  mysql:
    container_name: mysql_database
    image: mysql:8.0.20
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user_basic
      MYSQL_PASSWORD: password_basic
